### ISSUE TITLE
afk page crash

### ISSUE THREAD

**Issue by YTiceice** [Qwaekactyl/Qwaekactyl#6]
When i go to the afk page the server crashes with this error.
NodeJS version: v14.21.2
npm version: 6.14.17

```
[Qwaekactyl] Loaded Website on the port 34794 
(node:188245) UnhandledPromiseRejectionWarning: Error: Line 6: Unexpected token function
    at constructError (/root/Dashactyl/node_modules/javascript-obfuscator/node_modules/esprima/esprima.js:2407:21)
    at createError (/root/Dashactyl/node_modules/javascript-obfuscator/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/root/Dashactyl/node_modules/javascript-obfuscator/node_modules/esprima/esprima.js:2500:13)
    at throwUnexpectedToken (/root/Dashactyl/node_modules/javascript-obfuscator/node_modules/esprima/esprima.js:2505:15)
    at expect (/root/Dashactyl/node_modules/javascript-obfuscator/node_modules/esprima/esprima.js:2523:13)
    at expectCommaSeparator (/root/Dashactyl/node_modules/javascript-obfuscator/node_modules/esprima/esprima.js:2547:13)
    at parseArguments (/root/Dashactyl/node_modules/javascript-obfuscator/node_modules/esprima/esprima.js:3333:17)
    at parseLeftHandSideExpressionAllowCall (/root/Dashactyl/node_modules/javascript-obfuscator/node_modules/esprima/esprima.js:3426:24)
    at inheritCoverGrammar (/root/Dashactyl/node_modules/javascript-obfuscator/node_modules/esprima/esprima.js:2681:18)
    at parsePostfixExpression (/root/Dashactyl/node_modules/javascript-obfuscator/node_modules/esprima/esprima.js:3490:16)
```

**Comment by ItzCrazyKns** [comment]
Hey Please join our discord server https://discord.gg/JFG5eGZS our team will help you get out of this error
